image: rocker/tidyverse
stages:
    - test
test-job:
    stage: test
    script:
        - R -e 'devtools::load_all()'
        #- R CMD check ./ --no-manual
        - R -e 'devtools::test()'
        #- R -e 'devtools::install()'
