---
title: "vignette_basics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette_basics}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Load package

```{r setup}
library(compareid)
```


# Data

We're going to play with the package data, `table1` and `table2`.

```{r results = 'asis', echo = F}
knitr::kable(table1)
```

```{r results = 'asis', echo = F}
knitr::kable(table2)
```



# Data preparation

## select_id

We have to select the column that we want to work with:

```{r}
ids <- CompareID$new(table1, table2, "municipi")
ids
```

It returns a list with two tibbles, each with the selected column.


# Data exploration

## Tipus relació

```{r eval = F}
## Afegir recompte

join <- ids$id1["id"] |> 
  dplyr::inner_join(ids$id2 |> 
                     dplyr::distinct(.keep_all = TRUE), by = "id")
join

```



